# -*- coding: utf-8 -*-
"""heart_copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15p7t3iAzjIc626ACDGpNeBWqLRogEL_y
"""

pip install streamlit

import pickle
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.tree import DecisionTreeRegressor

filename = 'decision_tree_model_heart.pkl'
with open(filename, 'rb') as file:
    loaded_model = pickle.load(file)

st.title('Heart Failure Prediction App')
st.subheader('Please enter your data:')

df = pd.read_csv('/content/features (1).csv')
columns_list = df.columns.to_list()

uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)


    df = df.reindex(columns=columns_list, fill_value=0)

    prediction = loaded_model.predict(df)
    prediction_text = np.where(prediction == 1, 'Yes', 'No')
    st.subheader('HeartFailiure')
    st.write(prediction_text)

